<a href="https://colab.research.google.com/github/PatchavaKoushikChowdary/Birble-ai-/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
one_to_ten = torch.arange(start =0, end=11, step=1)
print(one_to_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [8]:
ten_zeros = torch.zeros_like(input =one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Tensor datatypes

In [9]:
 float_32_tensor = torch.tensor([3.0 , 6.0 , 9.0], dtype=None, device=None,requires_grad=False)
 print(float_32_tensor)

tensor([3., 6., 9.])


In [11]:
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


In [12]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [13]:
int_32_tensor =torch.tensor([3 , 6 , 9],dtype=torch.int64)
print(int_32_tensor)

tensor([3, 6, 9])


In [16]:
some_tensor =torch.rand(3,4)
print(some_tensor)

tensor([[0.8445, 0.1480, 0.4301, 0.3070],
        [0.7988, 0.4524, 0.9510, 0.4416],
        [0.9240, 0.3047, 0.7610, 0.0766]])


In [17]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.8445, 0.1480, 0.4301, 0.3070],
        [0.7988, 0.4524, 0.9510, 0.4416],
        [0.9240, 0.3047, 0.7610, 0.0766]])
Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


manipulating tensors

In [22]:
tensor =torch.tensor([1 , 2 , 3])
print(tensor + 10)
print(tensor - 10)

tensor([11, 12, 13])
tensor([-9, -8, -7])


In [23]:
tensor =torch.tensor([1 , 2 , 3])
print(tensor * 10)
print(tensor / 10)

tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


matrix multiplication

In [24]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.7558, 1.1346],
        [1.2516, 1.4503]])

In [25]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.1894, 0.7380, 0.8721],
        [0.1014, 0.4931, 0.7104],
        [0.0416, 0.1595, 0.1852]])

In [26]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[3.1183, 2.3817, 3.6040, 2.8289, 3.3894, 2.5036, 3.6308, 1.7593, 3.0509,
         3.2005],
        [3.3346, 2.9979, 3.9738, 3.2560, 3.7345, 2.9034, 3.9532, 1.9522, 3.5407,
         3.4947],
        [2.4149, 2.5276, 3.2318, 2.5786, 3.2515, 2.3061, 2.6711, 1.4767, 2.9349,
         2.5020],
        [3.1825, 2.1293, 3.2578, 2.8664, 3.3445, 2.2545, 3.3044, 2.0199, 2.5453,
         3.0196],
        [2.4611, 2.2501, 3.0310, 2.1914, 2.9581, 2.2736, 2.7789, 1.4317, 2.7203,
         2.6557],
        [3.1898, 2.5000, 3.5263, 2.7476, 3.8557, 2.2202, 3.1612, 2.1523, 2.4420,
         2.9636],
        [2.4720, 2.1127, 2.7943, 2.6601, 2.9129, 2.1570, 2.9757, 1.5057, 2.7683,
         2.5886],
        [2.9086, 2.1871, 2.9779, 2.0696, 2.7504, 1.6413, 3.2033, 1.6036, 2.2114,
         2.8188],
        [3.2466, 2.6006, 3.5926, 2.3632, 3.3474, 2.2932, 3.0808, 1.8280, 3.0559,
         3.2924],
        [3.3715, 2.8721, 3.4420, 2.5493, 3.0446, 2.3687, 3.1920, 1.8648, 3.0592,
         3.3804]])

In [27]:
print(tensor, "*" ,tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [29]:
print(tensor, "*" , tensor)
print(f"Equals:({tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:(tensor([1, 4, 9])


In [30]:
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 125 µs, sys: 0 ns, total: 125 µs
Wall time: 130 µs


tensor(14)

In [40]:
n=torch.arange(0,100,10)
n

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
torch.max(n)


tensor(90)

In [45]:
torch.min(n)

tensor(0)

In [46]:
torch.sum(n)

tensor(450)